spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성
    properties:
      hibernate:
#        show_sql: true # System.out 에 하이버네이트 실행 SQL을 남김
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false

logging.level:
  org.hibernate.SQL: debug # logger를 통해 하이버네이트 실행 SQL을 남김
#  org.hibernate.type: trace